// <auto-generated />
namespace FCK.Studio.EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddTenants : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddTenants));
        
        string IMigrationMetadata.Id
        {
            get { return "201803200631493_AddTenants"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
